# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

Widgets:
    resource: "@AcmeDemoBundle/Resources/config/routing/widgets.yml"
    prefix:   /widgets
